[2022-12-04T16:12:14.278+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_generation.generate_data scheduled__2022-12-03T03:00:00+00:00 [queued]>
[2022-12-04T16:12:14.285+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_generation.generate_data scheduled__2022-12-03T03:00:00+00:00 [queued]>
[2022-12-04T16:12:14.287+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T16:12:14.288+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-04T16:12:14.289+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T16:12:14.297+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): generate_data> on 2022-12-03 03:00:00+00:00
[2022-12-04T16:12:14.305+0000] {standard_task_runner.py:55} INFO - Started process 194 to run task
[2022-12-04T16:12:14.309+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_generation', 'generate_data', 'scheduled__2022-12-03T03:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmphd_hgc6b']
[2022-12-04T16:12:14.316+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask generate_data
[2022-12-04T16:12:14.384+0000] {task_command.py:389} INFO - Running <TaskInstance: data_generation.generate_data scheduled__2022-12-03T03:00:00+00:00 [running]> on host c7dedbf79ea9
[2022-12-04T16:12:14.441+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_generation
AIRFLOW_CTX_TASK_ID=generate_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T03:00:00+00:00
[2022-12-04T16:12:14.545+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-04T16:12:14.556+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=data_generation, task_id=generate_data, execution_date=20221203T030000, start_date=20221204T161214, end_date=20221204T161214
[2022-12-04T16:12:14.603+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-04T16:12:14.628+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
