[2022-12-04T16:13:15.381+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_generation.notification scheduled__2022-12-03T16:00:00+00:00 [queued]>
[2022-12-04T16:13:15.390+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_generation.notification scheduled__2022-12-03T16:00:00+00:00 [queued]>
[2022-12-04T16:13:15.392+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T16:13:15.394+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-04T16:13:15.396+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T16:13:15.407+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): notification> on 2022-12-03 16:00:00+00:00
[2022-12-04T16:13:15.423+0000] {standard_task_runner.py:55} INFO - Started process 366 to run task
[2022-12-04T16:13:15.434+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_generation', 'notification', 'scheduled__2022-12-03T16:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmp2nqk3riv']
[2022-12-04T16:13:15.441+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask notification
[2022-12-04T16:13:15.547+0000] {task_command.py:389} INFO - Running <TaskInstance: data_generation.notification scheduled__2022-12-03T16:00:00+00:00 [running]> on host c7dedbf79ea9
[2022-12-04T16:13:15.633+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_generation
AIRFLOW_CTX_TASK_ID=notification
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T16:00:00+00:00
[2022-12-04T16:13:15.636+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-04T16:13:15.653+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo received data at 2022-12-03']
[2022-12-04T16:13:15.667+0000] {subprocess.py:86} INFO - Output:
[2022-12-04T16:13:15.669+0000] {subprocess.py:93} INFO - received data at 2022-12-03
[2022-12-04T16:13:15.672+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-12-04T16:13:15.698+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=data_generation, task_id=notification, execution_date=20221203T160000, start_date=20221204T161315, end_date=20221204T161315
[2022-12-04T16:13:15.724+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-04T16:13:15.745+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
