[2022-12-04T16:13:38.788+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_generation.notification scheduled__2022-12-03T21:00:00+00:00 [queued]>
[2022-12-04T16:13:38.805+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_generation.notification scheduled__2022-12-03T21:00:00+00:00 [queued]>
[2022-12-04T16:13:38.806+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T16:13:38.807+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-04T16:13:38.808+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T16:13:38.824+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): notification> on 2022-12-03 21:00:00+00:00
[2022-12-04T16:13:38.852+0000] {standard_task_runner.py:55} INFO - Started process 427 to run task
[2022-12-04T16:13:38.858+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_generation', 'notification', 'scheduled__2022-12-03T21:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmp_4pq21b0']
[2022-12-04T16:13:38.868+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask notification
[2022-12-04T16:13:39.011+0000] {task_command.py:389} INFO - Running <TaskInstance: data_generation.notification scheduled__2022-12-03T21:00:00+00:00 [running]> on host c7dedbf79ea9
[2022-12-04T16:13:39.105+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_generation
AIRFLOW_CTX_TASK_ID=notification
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T21:00:00+00:00
[2022-12-04T16:13:39.108+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-04T16:13:39.115+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo received data at 2022-12-03']
[2022-12-04T16:13:39.144+0000] {subprocess.py:86} INFO - Output:
[2022-12-04T16:13:39.148+0000] {subprocess.py:93} INFO - received data at 2022-12-03
[2022-12-04T16:13:39.151+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-12-04T16:13:39.187+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=data_generation, task_id=notification, execution_date=20221203T210000, start_date=20221204T161338, end_date=20221204T161339
[2022-12-04T16:13:39.231+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-04T16:13:39.252+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
